### ISSUE TITLE
Foundry 0.8.x Support

### ISSUE THREAD

**Issue by Oromis** [grandseiken/foundryvtt-vehicles-and-mechanisms#11]
Hi, will you update this module for Foundry's 0.8.x branch?

No pressure, I know first hand how annoying breaking changes can be. I'd really appreciate it though!

**Comment by grandseiken** [comment]
Yep, getting Multilevel Tokens done first was a priority but I'll try to get to this one soon as well.

**Comment by Oromis** [comment]
Thanks a lot for your efforts!

**Comment by aprusik** [comment]
Just an fyi, I can't find this when searching in the foundry module-browser anymore. The manifest url still works though. Thanks for the 0.8.x update!
