### ISSUE TITLE
Player-controlled token as vehicle control does not function

### ISSUE THREAD

**Issue by asvetlovsky** [grandseiken/foundryvtt-vehicles-and-mechanisms#3]
I've set up a vehicle with a tile and multiple tokens, and a control token. Everything functions as intended as the GM. 

I've given ownership of the control token to a player, and they are able to move that token. However, the vehicle does not move at all in this case. This seems like a bug when compared to the description of the control token in the README:

> This can be used to control a vehicle remotely, to allow your players to control a vehicle (by granting them control of the token), or for other automation purposes.

**Comment by grandseiken** [comment]
I suspect the issue is you are testing without a GM logged in. A GM needs to be logged in for the module to function.

**Comment by asvetlovsky** [comment]
Apologies, that was the case. 

I had sought advice on Discord, but hadn't gotten to the bottom of this. I'm glad it's resolved.

Thank you.
