### ISSUE TITLE
Wall Collision setting prevents movement at all

### ISSUE THREAD

**Issue by Zamrod** [grandseiken/foundryvtt-vehicles-and-mechanisms#6]
When the Wall Collision setting is turned on for a drawing, moving the controller does not move any of the captured items at all in 0.7.5.

**Comment by grandseiken** [comment]
Yeah, I'm aware of this issue. Wall Collision is as far as I know the one feature that doesn't work properly on 0.7.x. Thanks for filing a ticket to remind me.
