### ISSUE TITLE
BUG: Token position degrades toward the center over time as you rotate

### ISSUE THREAD

**Issue by GambetTV** [grandseiken/foundryvtt-vehicles-and-mechanisms#9]
As you rotate the vehicle, tokens inside of it lose their position on the grid, and slowly move toward the center of the vehicle over time, even when the vehicle is perfectly aligned with the grid. This maybe can't be helped, but it makes things a bit tricky.

**Comment by nloew** [comment]
I found one reason, see my comment here: https://github.com/grandseiken/foundryvtt-multilevel-tokens/issues/74

Another is if you rotate before the token reached its final destination. If you wait for all tokens to be moved, it seems to work fine

**Comment by grandseiken** [comment]
Rotation inaccuracy should be fixed by updating to Multilevel Tokens v1.4.0 now. Thanks for the report.
